# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the build files from the previous stage
COPY build /usr/share/nginx/html

# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
