# Generated by Django 5.0.6 on 2024-06-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromLocation', models.CharField(max_length=100)),
                ('toLocation', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('fromWeather', models.JSONField()),
                ('toWeather', models.JSONField()),
                ('expenses', models.ManyToManyField(related_name='trips', to='expenses.expense')),
            ],
        ),
    ]
